# Generated by Django 5.0.1 on 2024-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='customer_photos/')),
                ('previous_purchases', models.TextField()),
            ],
        ),
    ]
