# Generated by Django 5.0.1 on 2024-05-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='previous_purchases',
        ),
    ]
